---
- name: Setup dotfiles
  hosts: localhost
  become_user: "{{ ansible_user_id }}"
  tasks:
    - name: clone dotfiles repository
      git: repo=https://github.com/flrnd/dotfiles.git
           dest={{ ansible_user_dir }}/.dotfiles
           update=no

    - name: create zsh symlink
      file: path={{ ansible_user_dir }}/.zsh
            src={{ ansible_user_dir }}/.dotfiles/zsh
            state=link

    - name: zshrc symlink
      file: path={{ ansible_user_dir }}/.zshrc
            src={{ ansible_user_dir }}/.zsh/config.zsh
            state=link

    - name: zshenv symlink
      file: path={{ ansible_user_dir }}/.zshenv
            src={{ ansible_user_dir }}/.zsh/env.zsh
            state=link

    - name: zshprofile symlink
      file: path={{ ansible_user_dir }}/.zshprofile
            src={{ ansible_user_dir }}/.zsh/env.zsh
            state=link


