---
- name: Install packages
  hosts: localhost
  sudo: no
  tasks:
    - name: upgrade all packages
      package:
        name: "*"
        state: latest
      sudo: yes

    - name: install packages
      package: name={{ item }}
               state=present
      with_items:
        - ack
        - bat
        - curl
        - git
        - gnome-tweaks
        - htop
        - httpie
        - fd-find
        - make
        - ncdu
        - neovim
        - pass
        - qrencode
        - ranger
        - ripgrep
        - tig
        - tilix
        - util-linux-user
        - virt-manager
        - xclip
        - zsh
      sudo: yes

    - name: set zsh as default shell
      command: "usermod --shell /usr/bin/zsh {{ ansible_user_id }}"
      sudo: yes

    - debug: var=ansible_user_id
