---
- name: Install packages
  hosts: localhost
  become: True
  tasks:
    - name: upgrade all packages
      package:
        name: "*"
        state: latest

    - name: install packages
      package: name={{ item }}
               state=present
      with_items:
        - ack
        - curl
        - git
        - htop
        - make
        - util-linux-user
        - neovim
        - zsh
        - bat
        - ripgrep
        - fd-find
        - ncdu
        - tig
        - tilix
