---
- name: Install rpmfusion repos
  hosts: localhost
  become: true
  tasks:
    - name: install rpmfusion free
      dnf:
        name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
        state: latest
