- name: Install rpmfusion repos
  hosts: localhost
  become: true
  tasks:
    - name: install rpmfusion repositories
      dnf:
        name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
        state: latest

    - name: install packages from rpmfusion
      dnf:
        name:
          - mpv
          - ffmpeg
          - libva-utils
