- name: Install Visual Studio Code
  hosts: localhost
  become: True
  become_user: root
  tasks:
    - name: set up vscode repo
      yum_repository:
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        description: Microsoft VS Code Repo
        enabled: yes
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        name: VisualStudioCode

    - name: Upgrade all packages
      package:
        name: "*"
        state: latest

    - name: Install vs code
      package:
        name: code
        state: present

